### PR TITLE
Override not editable fields during updates

### LINKED ISSUE #199: Unable to update InferenceService and ServeModel
**Describe the bug**
Unable to update `InferenceService` and `ServeModel` through the **proxy**, getting:

```
{"code":"","message":"strconv.Atoi: parsing \"\": invalid syntax"}

```

The issue is because going through the proxy user provide `*Update` entities that do not have NOT editable fields, e.g., `RegisteredModelId` for InferenceService - the core layer is expecting it as this is a required field for `InferenceService` objects.

**To Reproduce**
1. Create a new InferenceService
2. Try to update it using curl
```
url -X 'PATCH' \
  'http://localhost:8080/api/model_registry/v1alpha1/inference_services/5' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "modelVersionId": "3",
  "runtime": "model-server",
  "state": "UNDEPLOYED"
}'
```
3. See error
```
{"code":"","message":"strconv.Atoi: parsing \"\": invalid syntax"}

```

**Expected behavior**
All NOT EDITABLE fields should be automatically filled during the update.

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by lampajr**
Fixes https://github.com/opendatahub-io/model-registry/issues/199

## Description

As per related issue description, this PR aims to fix the update issue for `InferenceService` and `ServeModel`.
Created `OverrideNotEditableFor<Entity>` converters that take `<existing, update>` and override the NOT editable fields in the `update` object by taking those values from the `existing`.

With this approach I was able to remove the `Name` override in the core functions.

**NOTE**: everytime we add a new field in the openapi spec that can be editable, we should `ignore` it in the `OverrideNotEditableFor<Entity>` converters.

> Since I have updated the `goverter` version, I recommend to run `make clean/deps` and then `make build`  to download te proper version of goverter.

## How Has This Been Tested?

```
make test
```

## Merge criteria:

- [x] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [x] The developer has manually tested the changes and verified that the changes work

### CODE REVIEW

**Review by tarilabs — DISMISSED** [review]
Great catch! Thank you so much

As discussed offline, if there is a quick way via introspection/parsing to determine the `// annotation` so to make sure is updated with the list of fields using pointer semantic in the struct, it would be awesome.
If that takes too much time, could be postponed for later

**Comment by lampajr** [comment]
> As discussed offline, if there is a quick way via introspection/parsing to determine the `// annotation` so to make sure is updated with the list of fields using pointer semantic in the struct, it would be awesome. If that takes too much time, could be postponed for later

+1 I will try to investigate if there is an easy way to ensure that all fields that are editable are NOT overridden, keep you posted here.

**Comment by lampajr** [comment]
> +1 I will try to investigate if there is an easy way to ensure that all fields that are editable are NOT overridden, keep you posted here.

I think I have found a possible approach for testing this using reflection and inspection of the goverter methods directives. Hope to provide a proposal on Monday :)

File: internal/converter/openapi_converter_test.go [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+		}
+		v.t.Errorf("missing fields to be ignored for OverrideNotEditableFor* goverter methods:\n%v", missingFieldsMsg)
+	}
+}
+
+// checkEntity check if there are missing fields to be ignored in the override method
+func checkEntity(entity *oapiEntity) []string {
+	res := []string{}
+	objType := reflect.TypeOf(entity.obj)
+	for i := 0; i < objType.NumField(); i++ {
```
Comment (tarilabs) [inline internal/converter/openapi_converter_test.go:124]: I suspect there must be a way to make Field(s) iterable with `range` but it's not important for now

File: internal/converter/openapi_converter_test.go [hunk 2]
```diff
@@ -0,0 +1,160 @@
...
+	switch d := n.(type) {
+	case *ast.InterfaceType:
+		for _, m := range d.Methods.List {
+			methodName := m.Names[0].Name
+
+			if converterMethodPattern.MatchString(methodName) {
+				entityName := v.extractGroup(converterMethodPattern, methodName)
+				entity := v.getEntity(entityName)
+				// there should be just one doc comment matching ignoreDirectivePattern
+				for _, c := range m.Doc.List {
```
Comment (tarilabs) [inline internal/converter/openapi_converter_test.go:80]: I understand this extract all code comments pertaining to Methods. Nice, just as expected also from JavaParser AST I believe structure is analogous

**Review by tarilabs — APPROVED** [review]
Awesome! I understand works as expected, and the parser used is even in Go stdlib

File: internal/converter/openapi_converter_test.go (hunk 1 above)
Comment (lampajr) [reply internal/converter/openapi_converter_test.go:124]: TBH I couldn't find a different way to iterate over those fields, at least using the `reflect` pkg and types. But yeah we can figure out if we can improve it in a later iteration

File: internal/converter/openapi_converter_test.go (hunk 2 above)
Comment (lampajr) [reply internal/converter/openapi_converter_test.go:80]: yeah correct, it extracts all of them and then I just had to filter the one we are insterested in.

**Comment by lampajr** [comment]
Going to merge this to unblock the development of https://github.com/opendatahub-io/model-registry/issues/173
